version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mollidays-db
    environment:
      POSTGRES_DB: mollidays_db
      POSTGRES_USER: myo
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: mollidays-backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
        build:
          context: ./frontend
        container_name: mollidays-frontend
        ports:
          - "3000:3000"
        env_file:
        - ./frontend/.env.docker
        depends_on:
          - backend

  mongo:
    image: mongo:6.0
    container_name: mollidays-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  
    
volumes:
  pgdata:
  mongodata:
